### ISSUE TITLE
[BUG] StreamOutput write_v_int is broken

### ISSUE THREAD

**Issue by dbwiddis** [dblock/opensearch-sdk-py#5]
To reproduce:
```python
variable_header = StreamOutput()
variable_header.write_v_int(4)
```

Expected results:

The byte 0x04 appended to the output stream

Actual results:
```
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/Users/widdisd/git/opensearch-sdk-py/samples/hello/hello.py", line 65, in handle_connection
    variable_header.write_v_int(4)
  File "/Users/widdisd/git/opensearch-sdk-py/src/opensearch_sdk_py/transport/stream_output.py", line 20, in write_v_int
    return self.write(result)
           ^^^^^^^^^^^^^^^^^^
```

Analysis:

This implementation appears to define a string and append characters to it.  
```python
# writes an int in a variable-length format
def write_v_int(self, i: int):
    result = ''
    while True:
        result = chr((i & 0x7f) | 0x80) + result
        i >>= 7
        if ((i & ~0x7F) == 0):
            break
    return self.write(result)
```
This looks like it maybe would work if I could convert the string to bytes at the end, except the usual bytes() fails on lack of encoding and doesn't work for `ascii` because the values are higher than 128.  And there are a few more errors:
 - it prepends the character to the string, while vint appends them
 - it never writes the final byte after the loop break

This doesn't seem to match the implementation in OpenSearch where:
 - if the result can fit in a byte it shortcuts and writes the byte
 - it writes values less than 7 bytes but or's the high bit, appending to the end of the array
 - the final value is written without or'ing the high bit, which is how the reader knows to end reading the int

I've tried a few ways to fix it using bytearray and append but it's failing.  Working around it for now.

**Comment by dbwiddis** [comment]
Doh... realized why it's failing, it writes 0x84 because it always hits that first loop iteration.  Short-cutting single byte would probably fix that.
